// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: hasher.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashType int32

const (
	HashType_HASH_UNSPECIFIED HashType = 0
	HashType_HASH_SHA256      HashType = 1
	HashType_HASH_SHA512      HashType = 2
)

// Enum value maps for HashType.
var (
	HashType_name = map[int32]string{
		0: "HASH_UNSPECIFIED",
		1: "HASH_SHA256",
		2: "HASH_SHA512",
	}
	HashType_value = map[string]int32{
		"HASH_UNSPECIFIED": 0,
		"HASH_SHA256":      1,
		"HASH_SHA512":      2,
	}
)

func (x HashType) Enum() *HashType {
	p := new(HashType)
	*p = x
	return p
}

func (x HashType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashType) Descriptor() protoreflect.EnumDescriptor {
	return file_hasher_proto_enumTypes[0].Descriptor()
}

func (HashType) Type() protoreflect.EnumType {
	return &file_hasher_proto_enumTypes[0]
}

func (x HashType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashType.Descriptor instead.
func (HashType) EnumDescriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{0}
}

type HashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*HashRequestItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hasher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hasher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{0}
}

func (x *HashRequest) GetItems() []*HashRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type HashRequestItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type HashType `protobuf:"varint,2,opt,name=type,proto3,enum=hasher.HashType" json:"type,omitempty"`
	Data string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HashRequestItem) Reset() {
	*x = HashRequestItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hasher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequestItem) ProtoMessage() {}

func (x *HashRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_hasher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequestItem.ProtoReflect.Descriptor instead.
func (*HashRequestItem) Descriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{1}
}

func (x *HashRequestItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HashRequestItem) GetType() HashType {
	if x != nil {
		return x.Type
	}
	return HashType_HASH_UNSPECIFIED
}

func (x *HashRequestItem) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type HashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string              `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Items   []*HashResponseItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hasher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hasher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{2}
}

func (x *HashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HashResponse) GetItems() []*HashResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type HashResponseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *HashResponseItem) Reset() {
	*x = HashResponseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hasher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponseItem) ProtoMessage() {}

func (x *HashResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_hasher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponseItem.ProtoReflect.Descriptor instead.
func (*HashResponseItem) Descriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{3}
}

func (x *HashResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HashResponseItem) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_hasher_proto protoreflect.FileDescriptor

var file_hasher_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x0b, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x48, 0x61,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x5b, 0x0a, 0x0f, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x48,
	0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x58, 0x0a, 0x0c, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x3a, 0x0a, 0x10, 0x48,
	0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x42, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x41, 0x53,
	0x48, 0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x41,
	0x53, 0x48, 0x5f, 0x53, 0x48, 0x41, 0x35, 0x31, 0x32, 0x10, 0x02, 0x32, 0x42, 0x0a, 0x06, 0x48,
	0x61, 0x73, 0x68, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x12, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72,
	0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69,
	0x67, 0x68, 0x74, 0x6c, 0x6f, 0x72, 0x64, 0x31, 0x38, 0x39, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2d, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hasher_proto_rawDescOnce sync.Once
	file_hasher_proto_rawDescData = file_hasher_proto_rawDesc
)

func file_hasher_proto_rawDescGZIP() []byte {
	file_hasher_proto_rawDescOnce.Do(func() {
		file_hasher_proto_rawDescData = protoimpl.X.CompressGZIP(file_hasher_proto_rawDescData)
	})
	return file_hasher_proto_rawDescData
}

var file_hasher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hasher_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hasher_proto_goTypes = []interface{}{
	(HashType)(0),            // 0: hasher.HashType
	(*HashRequest)(nil),      // 1: hasher.HashRequest
	(*HashRequestItem)(nil),  // 2: hasher.HashRequestItem
	(*HashResponse)(nil),     // 3: hasher.HashResponse
	(*HashResponseItem)(nil), // 4: hasher.HashResponseItem
}
var file_hasher_proto_depIdxs = []int32{
	2, // 0: hasher.HashRequest.items:type_name -> hasher.HashRequestItem
	0, // 1: hasher.HashRequestItem.type:type_name -> hasher.HashType
	4, // 2: hasher.HashResponse.items:type_name -> hasher.HashResponseItem
	1, // 3: hasher.Hasher.GetHashes:input_type -> hasher.HashRequest
	3, // 4: hasher.Hasher.GetHashes:output_type -> hasher.HashResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hasher_proto_init() }
func file_hasher_proto_init() {
	if File_hasher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hasher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hasher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashRequestItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hasher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hasher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashResponseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hasher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hasher_proto_goTypes,
		DependencyIndexes: file_hasher_proto_depIdxs,
		EnumInfos:         file_hasher_proto_enumTypes,
		MessageInfos:      file_hasher_proto_msgTypes,
	}.Build()
	File_hasher_proto = out.File
	file_hasher_proto_rawDesc = nil
	file_hasher_proto_goTypes = nil
	file_hasher_proto_depIdxs = nil
}
